name: Build and Push to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Tags
        env:
          ref1: ${{ github.ref}}
          ref: 2.2.32-016.41.17
          repo: ${{ github.repository }}
        run: |
          if [[ $ref == master ]]; then
            tags=$repo:unstable
          elif [[ $ref =~ ^([0-9.]+)-((([0-9]+[.])[0-9]+[.])([.][0-9+])*)  ]]; then
            upstream=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[3]}x
            major=${BASH_REMATCH[4]}x
            tags=$repo:latest,$repo:$ref,$repo:$upstream-$minor,$repo:$upstream-$major,$repo:upstream
          else
            echo "Bad tag: $ref"
            exit 1
          fi
          echo "$tags"
          echo "build_tags=$tags" >> $GITHUB_ENV
          exit 1
