name: Build and Push to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: "7.1.33"
            os: "3.9"
          - php: "7.2.26"
            os: "3.9"
    steps:
      - name: Extract PHP Versions
        id: phpver
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          tags: 'type=semver,pattern={{major}}.{{minor}},value=${{ matrix.php }}'
          flavor: 'latest=false'

      - name: Calculate Tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }},ghcr.io/${{ github.repository }}
          flavor: 'latest=false'
          tags: |
            type=semver,pattern={{version}},prefix=${{ matrix.php }}-,value=2.1.3
            type=semver,pattern={{major}}.{{minor}}.x,prefix=${{ matrix.php }}-,value=2.1.3
            type=semver,pattern={{major}}.x,prefix=${{ matrix.php }}-,value=2.1.3
            type=raw,value=${{ matrix.php }}
            type=semver,pattern=${{ steps.phpver.outputs.version }}-{{version}},value=2.15.3
            type=semver,pattern=${{ steps.phpver.outputs.version }}-{{major}}.{{minor}}.x,value=2.15.3
            type=semver,pattern=${{ steps.phpver.outputs.version }}-{{major}}.x,value=2.15.3
            type=raw,value=${{ steps.phpver.outputs.version }}
