name: Build and Push to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: "7.1.33"
            os: "3.9"
          - php: "7.2.26"
            os: "3.9"
    steps:
      - name: Extract PHP Versions
        id: phpver
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          tags: 'type=semver,pattern={{major}}.{{minor}},value=${{ matrix.php }}'
          flavor: 'latest=false'

      - name: Calculate Tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          tags: |
            type=semver,pattern=-{{version}},value=2.1.1
            type=semver,pattern=-{{major}}.{{minor}},value=2.1.1
            type=semver,pattern=-{{major}}.x,value=2.1.1
            type=raw,value=
          flavor: |
            latest=false
            prefix=${{ matrix.php }}
            prefix=${{ steps.phpver.outputs.version }}
