name: Build and Push to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.1.33", "7.2.26", "7.3.13"]
    steps:
      - name: Extract PHP Versions
        id: phpver
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          sep-tags: ","
          tags: |
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.php }}
          flavor: |
            latest=false      
      - name: Calculate Tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          sep-tags: ","
          tags: |
            type=semver,pattern={{version}},value=2.1.0
            type=semver,pattern={{major}}.{{minor}},value=2.1.0
            type=semver,pattern={{major}}.x,value=2.1.0
          flavor: |
            latest=true
            prefix=${{ matrix.php }}-,onlatest=true
            prefix=${{ steps.phpver.output.version }}-,onlatest=true
